[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
<<<<<<< HEAD
chain_fund_me = "Ej3tE117rHTNG6rJwrikXB45XXYJefiBUJMmv5GqmeNQ"
=======
chain_fund_me = "4fG2iXUACiXzGSkVptNY9hwfPThohA3yrjKpfajFCH3y"
>>>>>>> origin/main

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
